//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECARD.DL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity_master
    {
        public long sno { get; set; }
        public string code { get; set; }
        public Nullable<long> msno { get; set; }
        public string mname { get; set; }
        public string descript { get; set; }
        public string activity_status { get; set; }
        public string posted_by { get; set; }
        public System.DateTime posted_date { get; set; }
        public string s_r_det { get; set; }
    
        public virtual modules_master modules_master { get; set; }
    }
}
