//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECARD.DL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class arights_master
    {
        public long sno { get; set; }
        public string rcode { get; set; }
        public string rdesc { get; set; }
        public string radmin { get; set; }
        public string role_status { get; set; }
        public Nullable<long> emp_detail_id { get; set; }
        public string usernaem { get; set; }
        public string mcode { get; set; }
        public string mname { get; set; }
        public string module_status { get; set; }
        public string acode { get; set; }
        public string adescript { get; set; }
        public string aadd { get; set; }
        public string aview { get; set; }
        public string asearch { get; set; }
        public string aupdate { get; set; }
        public string adelete { get; set; }
        public string posted_by { get; set; }
        public System.DateTime posted_date { get; set; }
    }
}
