//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECARD.DL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class card_measurement
    {
        public long card_meas_sno { get; set; }
        public Nullable<long> event_det_sno { get; set; }
        public string card_size { get; set; }
        public string template { get; set; }
        public Nullable<int> qrcodesize { get; set; }
        public string qrleft { get; set; }
        public string qrtop { get; set; }
        public Nullable<int> element_font_size { get; set; }
        public string element_italic { get; set; }
        public string element_underline { get; set; }
        public string element_textalign { get; set; }
        public string element_color { get; set; }
        public string element_font_name { get; set; }
        public string element_left { get; set; }
        public string element_top { get; set; }
        public string element_bold { get; set; }
        public Nullable<int> cardsize_font_size { get; set; }
        public string cardsize_italic { get; set; }
        public string cardsize_underline { get; set; }
        public string cardsize_textalign { get; set; }
        public string cardsize_color { get; set; }
        public string cardsize_font_name { get; set; }
        public string cardsize_left { get; set; }
        public string cardsize_top { get; set; }
        public string cardsize_bold { get; set; }
        public Nullable<int> label_font_size { get; set; }
        public string label_italic { get; set; }
        public string label_underline { get; set; }
        public string label_textalign { get; set; }
        public string label_color { get; set; }
        public string label_font_name { get; set; }
        public string label_left { get; set; }
        public string label_top { get; set; }
        public string label_bold { get; set; }
        public Nullable<int> digit_font_size { get; set; }
        public string digit_italic { get; set; }
        public string digit_underline { get; set; }
        public string digit_textalign { get; set; }
        public string digit_color { get; set; }
        public string digit_font_name { get; set; }
        public string digit_left { get; set; }
        public string digit_top { get; set; }
        public string digit_bold { get; set; }
        public string misc_column1 { get; set; }
        public string misc_column2 { get; set; }
        public string misc_column3 { get; set; }
        public string misc_column4 { get; set; }
        public string misc_column5 { get; set; }
        public string posted_by { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
    
        public virtual event_details event_details { get; set; }
    }
}
