//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECARD.DL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class cash_collection
    {
        public long cash_col_sno { get; set; }
        public Nullable<long> event_det_sno { get; set; }
        public Nullable<long> contri_det_sno { get; set; }
        public string contributor_name { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string remarks { get; set; }
        public string posted_by { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
        public Nullable<System.DateTime> coll_date { get; set; }
    
        public virtual contributor_details contributor_details { get; set; }
        public virtual event_details event_details { get; set; }
    }
}
