//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECARD.DL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class con_notificaiton_master
    {
        public long con_notif_sno { get; set; }
        public Nullable<long> event_det_sno { get; set; }
        public Nullable<System.DateTime> intimate_date { get; set; }
        public Nullable<int> intimate_days { get; set; }
        public string posted_by { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
    
        public virtual event_details event_details { get; set; }
    }
}
