//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECARD.DL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class contributor_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contributor_details()
        {
            this.cash_collection = new HashSet<cash_collection>();
        }
    
        public long contri_det_sno { get; set; }
        public Nullable<long> event_det_sno { get; set; }
        public Nullable<long> cust_reg_sno { get; set; }
        public string contributor_name { get; set; }
        public string currency_code { get; set; }
        public Nullable<decimal> contribution_amount { get; set; }
        public Nullable<int> no_of_persons { get; set; }
        public string mobile_no { get; set; }
        public string email_address { get; set; }
        public string contri_status { get; set; }
        public string control_no { get; set; }
        public Nullable<System.DateTime> contri_due_date { get; set; }
        public string posted_by { get; set; }
        public System.DateTime posted_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cash_collection> cash_collection { get; set; }
        public virtual customer_registration customer_registration { get; set; }
        public virtual event_details event_details { get; set; }
    }
}
