//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECARD.DL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class contents_template_master
    {
        public long cont_mas_sno { get; set; }
        public string messaging_service_sid { get; set; }
        public string content_sid { get; set; }
        public string content_name { get; set; }
        public string content_code { get; set; }
        public string content_variables { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
        public string posted_by { get; set; }
        public string effective_date { get; set; }
        public string misc_column1 { get; set; }
        public string misc_column2 { get; set; }
    }
}
