//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECARD.DL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class cust_users
    {
        public long cust_users_sno { get; set; }
        public Nullable<long> cust_reg_sno { get; set; }
        public string user_fullname { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string user_type { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public string email_address { get; set; }
        public string mobile_no { get; set; }
        public string f_login { get; set; }
        public Nullable<int> log_att { get; set; }
        public Nullable<System.DateTime> log_time { get; set; }
        public string log_status { get; set; }
        public string posted_by { get; set; }
        public System.DateTime posted_date { get; set; }
        public string event_det_sno { get; set; }
    
        public virtual customer_registration customer_registration { get; set; }
    }
}
