//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECARD.DL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_detail
    {
        public long emp_detail_id { get; set; }
        public string emp_id_no { get; set; }
        public string full_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public Nullable<long> desg_id { get; set; }
        public string email_id { get; set; }
        public string username { get; set; }
        public string pwd { get; set; }
        public string mobile_no { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public string f_login { get; set; }
        public string app_status { get; set; }
        public Nullable<int> log_att { get; set; }
        public Nullable<System.DateTime> log_time { get; set; }
        public string log_status { get; set; }
        public string emp_status { get; set; }
        public string localization { get; set; }
        public string flag { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public string posted_by { get; set; }
        public System.DateTime posted_date { get; set; }
    }
}
