//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECARD.DL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class exception_error_logs
    {
        public long exce_err_sno { get; set; }
        public string triggered { get; set; }
        public string method { get; set; }
        public string exception { get; set; }
        public string trycatch { get; set; }
        public string class_name { get; set; }
        public string message { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
        public string posted_by { get; set; }
        public string misc_column1 { get; set; }
        public string misc_column2 { get; set; }
    }
}
