//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECARD.DL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class expenditure_details
    {
        public long exp_det_sno { get; set; }
        public Nullable<long> budget_mas_sno { get; set; }
        public Nullable<long> event_det_sno { get; set; }
        public string exp_item { get; set; }
        public Nullable<int> exp_qty { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public string remarks { get; set; }
        public string name_of_service_provider { get; set; }
        public string sp_contact_details { get; set; }
        public string posted_by { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
    
        public virtual budget_master budget_master { get; set; }
        public virtual event_details event_details { get; set; }
    }
}
