//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECARD.DL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class participant
    {
        public long pat_sno { get; set; }
        public string fullname { get; set; }
        public string phone_number { get; set; }
        public string gender { get; set; }
        public string dob { get; set; }
        public Nullable<long> region { get; set; }
        public Nullable<long> district { get; set; }
        public Nullable<long> ward { get; set; }
        public string posted_by { get; set; }
        public System.DateTime posted_date { get; set; }
        public string entrepreneur_status { get; set; }
        public string opportunity { get; set; }
        public string business_sector { get; set; }
        public string ip_address { get; set; }
    }
}
