//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECARD.DL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class qr_verify_details
    {
        public long qr_ver_det_sno { get; set; }
        public Nullable<long> visitor_det_sno { get; set; }
        public Nullable<long> event_det_sno { get; set; }
        public Nullable<long> cust_reg_sno { get; set; }
        public string qrcode { get; set; }
        public Nullable<System.DateTime> event_start_time { get; set; }
        public Nullable<long> card_state_mas_sno { get; set; }
        public Nullable<int> no_of_persons { get; set; }
        public string scan_status { get; set; }
        public string posted_by { get; set; }
        public System.DateTime posted_date { get; set; }
    
        public virtual card_state_master card_state_master { get; set; }
        public virtual customer_registration customer_registration { get; set; }
        public virtual event_details event_details { get; set; }
        public virtual visitor_details visitor_details { get; set; }
    }
}
