//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECARD.DL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_event_text
    {
        public long sms_e_t_sno { get; set; }
        public Nullable<long> event_det_sno { get; set; }
        public Nullable<long> s_e_i_sno { get; set; }
        public string sms_text { get; set; }
        public string card_size { get; set; }
        public string includes { get; set; }
        public string excludes { get; set; }
        public string posted_by { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
    
        public virtual event_details event_details { get; set; }
        public virtual sms_email_instances sms_email_instances { get; set; }
    }
}
