//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECARD.DL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class twilio_notification_log
    {
        public long sno { get; set; }
        public string account_sid { get; set; }
        public string sms_sid { get; set; }
        public string api_version { get; set; }
        public Nullable<System.DateTime> received_at { get; set; }
        public string sms_status { get; set; }
        public string channel_install_sid { get; set; }
        public string channel_to_address { get; set; }
        public string messaging_service_sid { get; set; }
        public string message_status { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
        public string posted_by { get; set; }
        public string channel_prefix { get; set; }
        public string misc_column1 { get; set; }
        public string misc_column2 { get; set; }
        public string misc_column3 { get; set; }
        public string whatsapp_from { get; set; }
        public string whatsapp_to { get; set; }
        public string messaging_sid { get; set; }
    }
}
