//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECARD.DL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ward_master
    {
        public long ward_sno { get; set; }
        public string ward_name { get; set; }
        public Nullable<long> region_id { get; set; }
        public Nullable<long> district_sno { get; set; }
        public string ward_status { get; set; }
        public string posted_by { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
    
        public virtual district_master district_master { get; set; }
        public virtual region_master region_master { get; set; }
    }
}
