//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECARD.DL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class webhook_error_log
    {
        public long sno { get; set; }
        public string account_sid { get; set; }
        public string sid { get; set; }
        public string parent_account_sid { get; set; }
        public Nullable<System.DateTime> received_at { get; set; }
        public string level { get; set; }
        public string payload_type { get; set; }
        public string payload { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
        public string posted_by { get; set; }
        public string misc_column1 { get; set; }
        public string misc_column2 { get; set; }
        public Nullable<System.DateTime> misc_column3 { get; set; }
    }
}
