//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECARD.DL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class whatsapp_master
    {
        public long whats_mas_sno { get; set; }
        public string account_sid { get; set; }
        public string auth_token { get; set; }
        public string whatsapp_sender { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
        public string posted_by { get; set; }
        public string callback_url { get; set; }
        public string webhook_incoming { get; set; }
        public string webhook_error_log { get; set; }
        public string effective_date { get; set; }
        public string misc_column1 { get; set; }
        public string misc_column2 { get; set; }
        public string misc_column3 { get; set; }
    }
}
